#!/bin/bash

   	old_suffix=$1
   	new_suffix=$2
	if [ "$#" != 2 ]; then 
		echo
		echo ERROR: Must provide 2 arguments
	        echo Usage: ./rn c cpp >&2
		echo
	else
	
	   	for f in *.$old_suffix
   		do
       			 new_name=${f%.*}.$new_suffix
       			 echo Rename $f to $new_name
			 mv $f $new_name
   		done
	fi
